version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env.production
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appsistencia_net

  backend:
    build:
      context: ./back
    restart: always
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - appsistencia_net

  frontend:
    build:
      context: ./front
    restart: always
    env_file:
      - .env.production
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appsistencia_net

volumes:
  db_data:

networks:
  appsistencia_net: