version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: appsistencia
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./back
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: supersecret
      DB_NAME: appsistencia
      DATABASE_URL: postgres://postgres:supersecret@db:5432/appsistencia
    ports:
      - "3000:3000"
    depends_on:
      - db

  # frontend:
  #   build: ./front
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend

volumes:
  db_data:
