
services:
  db:
    image: postgres:16
    restart: always

    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appsistencia_net

  backend:
    build:
      context: ./back
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - appsistencia_net

  frontend:
    build:
      context: ./front
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appsistencia_net

volumes:
  db_data:

networks:
  appsistencia_net: